---
- name: Get CLDB FQDNs
  set_fact: cldb_item={{ hostvars[item]['ansible_fqdn'] if 'ansible_fqdn' in hostvars[item] else item  }}
  with_items:
    - "{{ groups['mapr-cldb'] }}"
  register: cldb_hosts
- name: Make CLDB String
  set_fact: cldb_string={{ cldb_hosts.results | map(attribute='ansible_facts.cldb_item') | list | join(',')}}

- name: Debug CLDB
  debug: msg="{{ cldb_string }}"


