- name: apply common configuration to all nodes
  hosts: master
  roles:
    - ../roles/ui-setup-nativesecurity-genkeys
- name: apply security
  hosts: all
  roles:
    - ../roles/ui-setup-nativesecurity-secure