---
- name: Install Kerberos 5 client
  vars:
    packages_RedHat: ['krb5-workstation', 'krb5-libs', "openldap-clients", "python-ldap"]
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
- name: Configure krb5.conf
  template: src=krb5.conf dest=/etc/krb5.conf