---
# Install HBase CLI
- name: Install mapr-hbase
  package: name=mapr-hbase state=present
- name: Set MAPR_HBASE_SERVER_OPTS using HYBRID_LOGIN_OPTS
  lineinfile: >
    dest=/opt/mapr/conf/env_override.sh
    line="export MAPR_HBASE_CLIENT_OPTS=\"${HYBRID_LOGIN_OPTS}\""
    regexp="^export MAPR_HBASE_CLIENT_OPTS"
    mode=0644
    create=yes
    owner="{{ mapr_user }}"
    group="{{ mapr_group }}"
  when: hbase_thrift_rest_security == 'kerberos'