- name: Retrieve all HistoryServer changes
  set_fact: historyserver_changes_item={{ hostvars[item]['historyserver_haschanged'] if 'historyserver_haschanged' in hostvars[item] else 0 }}
  with_items:
    - "{{ groups['all'] }}"
  register: historyserver_changes_hosts
- name: Calculate number of History Server changes
  set_fact: historyserver_changes={{ historyserver_changes_hosts.results | map(attribute='ansible_facts.historyserver_changes_item') | map('int') | sum }}
