---
- name: Install SSSD
  vars:
    packages_RedHat: ['samba-winbind', 'sssd', 'samba-common', 'samba-client', 'authconfig', 'openldap-clients', 'oddjob', 'oddjob-mkhomedir', 'adcli']
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"
- name: Configure sssd.conf
  template: src=sssd.conf dest=/etc/sssd/sssd.conf
- name: Set /etc/sssd/sssd.conf to chmod 400
  file: path=/etc/sssd/sssd.conf mode=0400
- name: Configure smb.conf
  template: src=smb.conf dest=/etc/samba/smb.conf
- name: Join to Windows domain
  shell: echo '{{ mapr_kerberos_admin_bind_pw }}' | net ads join -U {{ mapr_kerberos_admin }}
- name: Enable and start the SSSD  service
  service: name=sssd state=restarted enabled=yes
- name: Change PAM configuration with Redhat authconfig
  shell: authconfig --enablesssd --enablesssdauth  --disablekrb5 --enablemkhomedir --update --enablecache
