---
# Configure unsecure cluster

- name: Configure.sh
  shell: "/opt/mapr/server/configure.sh -N {{ cluster_name }} -Z {{ zookeeper_string }} -C {{ cldb_string }} -u {{ mapr_user }} -g {{mapr_group}} -unsecure -HS {{ historyserver_string }} {{ '--isvm' if virtual_machine else '' }}"
# mfs_heapsize_percent is optional, if required just remove # and set value, default is 35.
- name: Set MFS memory percent
  lineinfile: dest=/opt/mapr/conf/warden.conf regexp="^service\.command\.mfs\.heapsize\.maxpercent=" line="service.command.mfs.heapsize.maxpercent={{ mfs_heapsize_maxpercent }}"
  when: mfs_heapsize_maxpercent is defined