---
# Uninstall File Migrate Service
- name: Stop File Migrate Service
  shell: "maprcli node services -name filemigrate -action stop -nodes {{ ansible_fqdn }}"
  register: maprcli_result
  failed_when: maprcli_result.rc > 1
  changed_when: maprcli_result.rc == 0
  environment:
    MAPR_TICKETFILE_LOCATION: /opt/mapr/conf/mapruserticket
- name: Uninstall mapr-filemigrate
  package: name=mapr-filemigrate state=absent
