---
# Uninstall MySQL
- name: Uninstall MySQL / MariaDB
  vars:
    packages_Suse: ['mariadb']
    packages_RedHat: ['mariadb-server']
    packages_Debian: ['mysql-server']
  package: name={{ item }} state=absent
  with_items: "{{ vars['packages_' + ansible_os_family] }}"



