---
# Install MapR OpenTSDB

- name: Install mapr-opentsdb
  package: name=mapr-opentsdb state=present
- name: Get OpenTSDB version
  shell: cat /opt/mapr/opentsdb/opentsdbversion
  register: version_output
  check_mode: no
  changed_when: no

- name: Register higher memory for OpenTSDB in Warden - service.heapsize.min
  lineinfile: dest="/opt/mapr/opentsdb/opentsdb-{{ version_output.stdout }}/etc/conf/warden.opentsdb.conf" regexp="^service\.heapsize\.min=" line="service.heapsize.min={{ spyglass_opentsdb_max_memory_in_mb }}"
- name: Register higher memory for OpenTSDB in Warden - service.heapsize.max
  lineinfile: dest="/opt/mapr/opentsdb/opentsdb-{{ version_output.stdout }}/etc/conf/warden.opentsdb.conf" regexp="^service\.heapsize\.max=" line="service.heapsize.max={{ spyglass_opentsdb_max_memory_in_mb }}"
- name: Copy to /opt/mapr/conf/conf.d/warden.opentsdb.conf
  copy: remote_src=true src="/opt/mapr/opentsdb/opentsdb-{{ version_output.stdout }}/etc/conf/warden.opentsdb.conf" dest=/opt/mapr/conf/conf.d/warden.opentsdb.conf mode=0644 owner="{{ mapr_user }}" group="{{ mapr_group }}"
- name: Register higher memory for OpenTSDB in service script
  lineinfile: dest="/opt/mapr/opentsdb/opentsdb-{{ version_output.stdout }}/etc/init.d/opentsdb" regexp="^export JVMARGS" line="export JVMARGS='-enableassertions -enablesystemassertions -Xmx{{ spyglass_opentsdb_max_memory_in_mb }}m -Xss1m -XX:MaxMetaspaceSize=128m'"