---
# Install NFS
- name: Install mapr-nfs
  vars:
    packages_Suse: ['mapr-loopbacknfs', 'nfs-utils', 'rpcbind']
    packages_RedHat: ['mapr-loopbacknfs', 'nfs-utils', 'rpcbind']
    packages_Debian: ['mapr-loopbacknfs', 'nfs-common', 'rpcbind']
  package: name={{ item }} state=present
  with_items: "{{ vars['packages_' + ansible_os_family] }}"

# Other actions
- name: Copy mapr-clusters.conf
  copy: remote_src=True src=/opt/mapr/conf/mapr-clusters.conf dest=/usr/local/mapr-loopbacknfs/conf/mapr-clusters.conf
- name: Start NFS Loopback
  service: name=mapr-loopbacknfs state=restarted enabled=yes
- name: Create /mapr dir
  file: path=/mapr state=directory
- name: Mount /mapr
  mount: name=/mapr state=mounted src=localhost:/mapr fstype=nfs opts=hard,nolock

