---
# Uninstall mapr-posix-client-basic
- name: Check if Service Exists
  stat: path=/etc/init.d/mapr-posix-client-basic
  register: service_status
- name: Stop the mapr-posix-client-basic service
  service: name=mapr-posix-client-basic state=stopped
  when: service_status.stat.exists
- name: Uninstall mapr-posix-client-basic
  package: name=mapr-posix-client-basic state=absent
# Other actions
# - name: Remove /mapr dir
#   file: path=/mapr state=absent
